# Generated by Django 2.1.5 on 2019-02-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_feature_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_1', models.FloatField()),
                ('label', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shoptext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('restaurant_id', models.IntegerField()),
                ('description', models.TextField()),
                ('menus', models.TextField()),
            ],
        ),
    ]
